Task/password reset
Kintull/gpanel pull request #8
Opened 2021-04-15 12:47 UTC by cybernetlab

2021-04-16 23:40 UTC, Kintull requested changes

2021-04-16 23:40 UTC, Kintull commented on lib/gpanel_web/controllers/password_reset_controller.ex
> +  @reset_token_ttl 900 # 15 minutes
Could you please explain how two kinds of ttl work together?

2021-04-16 23:40 UTC, Kintull commented on lib/gpanel_web/controllers/password_reset_controller.ex
> +        token = Token.sign(@token_secret, @token_salt, user.id)
Link that is inserted in password reset mail can be used several times,do you think it is safe enough to leave it like this having only ttl check configured?

2021-04-17 07:00 UTC, cybernetlab commented on lib/gpanel_web/controllers/password_reset_controller.ex
> +  @reset_token_ttl 900 # 15 minutes
there are two kind of tokens:
1. Token that we receive as a parameter from password reset link when user clicks on emailed link (call it reset token).
2. After that we need to pass user-id to password-reset controller. It's not safe to use session or direct parameters for this. So we create another token (call it resetting token) and verifying it before reset password. This is temporary token to pass user-id between two controller actions.

2021-04-17 07:03 UTC, cybernetlab commented on lib/gpanel_web/controllers/password_reset_controller.ex
> +        token = Token.sign(@token_secret, @token_salt, user.id)
password reset via email is not enough secured by design. I'm sure that we need to implement something like 2fa for this in future. Anyway I don't know other ways to authenticate user in this scenario.

2021-04-17 07:07 UTC, cybernetlab commented on lib/gpanel_web/templates/password_reset/reset.html.eex
> +            <input type="password" name="prev_password" class="register-form-control" placeholder="Previous password" required />
haha, I've got carried away a bit )) Sure - where shouldn't be a prev password field

2021-05-06 17:01 UTC, merged